version: '3.8'

volumes:
  postgres_data:
  static_sp2:
  media_sp2:
  logs_sp2:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: matakov/yamdb:latest
    container_name: django
    restart: always
    environment:
      - PORT=8000
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - static_sp2:/code/static
      - media_sp2:/code/media

  nginx:
    # build: ./nginx
    image: nginx:1.19.0-alpine
    ports:
      - "127.0.0.1:8888:80"
    volumes:
      - static_sp2:/code/static
      - media_sp2:/code/media
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - web
    restart: "on-failure"