version: '3.8'

volumes:
  postgres_data:
  static_sp2:
  media_sp2:
  nginx_conf:

services:
  db:
    image: postgres:12.4
    volumes:
    restart: always
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  django:
    image: matakov/yamdb:latest
    environment:
      - PORT=8000
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    volumes:
      - static_sp2:/code/static
      - media_sp2:/code/media
      - nginx_conf:/code/nginx/
    entrypoint: /code/entrypoint.sh

  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "127.0.0.1:8888:80"
    volumes:
      - static_sp2:/code/static
      - media_sp2:/code/media
      - nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always